### ISSUE TITLE
Kerning vs Leading vs Tracking and how to use these in Site Editor - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1249]
# Topic Description
Using full site editing, demonstrate how to adjust the spacing between letters in headings and any other locations that are possible in WordPress.

# Related Resources
- See Letter Spacing on https://make.wordpress.org/core/2022/09/30/whats-new-in-gutenberg-14-2-28-september/
- What is Kearning vs Leading vs Tracking https://www.shutterstock.com/blog/differences-kerning-leading-tracking-typography

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the workshop
- [ ] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Tutorial published on WPTV
- [ ] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [ ] Tutorial created on Learn.WordPress.org
- [ ] Tutorial post is reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial announced to training team
- [ ] Tutorial announced to creator
- [ ] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by askdesign** [comment]
I see a mis-spell. It should be:
"Kerning" (not "Kearning")

**Comment by kaitohm** [comment]
I'm closing this as low-priority, as brought up in #1248 .
