### ISSUE TITLE
Using post meta

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2181]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title:  Plugin requirements
- Topic description: Learn how to use post meta to add custom fields to custom post types. Introduce the Custom Fields panel to manage custom fields. 
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe what a custom post type is
- Create a custom post type, using the relevant core function

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/metadata/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: 

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-plugins/04-custom-post-type-data.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/cbc559ea-2bd7-4f76-a748-6ab689f9bd93

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

----- 

I haven't spent much time digging into post meta. I should! Good info @jonathanbossenger

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/custom-post-type-data/
