### ISSUE TITLE
Test Playground Block on Learn WordPress.

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2352]
Once #2264 is merged and deployed, let's create a test/example lesson in preview mode, and test the playground block.

## Test page

You can test the playground block in both default and code view mode at the following URL
- https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/

## Issues list

- [ ] https://github.com/WordPress/playground-tools/issues/293
- [x] https://github.com/WordPress/playground-tools/issues/292
- [ ] https://github.com/WordPress/playground-tools/issues/291
- [x] https://github.com/WordPress/playground-tools/issues/289
- [x] https://github.com/WordPress/playground-tools/issues/288
- [x] https://github.com/WordPress/playground-tools/issues/286
- [x] https://github.com/WordPress/playground-tools/issues/279
- [ ] https://github.com/WordPress/playground-tools/issues/316
- [ ] https://github.com/WordPress/playground-tools/issues/290
- [ ] https://github.com/WordPress/playground-tools/issues/330
- [ ] https://github.com/WordPress/playground-tools/issues/331
- [ ] https://github.com/WordPress/playground-tools/issues/343
- [x] https://github.com/WordPress/playground-tools/issues/344

**Comment by bsanevans** [comment]
//dev

**Comment by jonathanbossenger** [comment]
Test page: https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/

**Comment by brandonpayton** [comment]
Hi @jonathanbossenger, a new version of the Playground block (interactive-code-block) has been released (v0.2.11) and contains updates to address the following issues:

- [ ] https://github.com/WordPress/playground-tools/issues/293
- [x] https://github.com/WordPress/playground-tools/issues/292
- [ ] https://github.com/WordPress/playground-tools/issues/291
- [x] https://github.com/WordPress/playground-tools/issues/289
- [x] https://github.com/WordPress/playground-tools/issues/288
- [x] https://github.com/WordPress/playground-tools/issues/286
- [x] https://github.com/WordPress/playground-tools/issues/279

Most of these issues are left open until we can confirm they are indeed fixed.

Today, the remaining issues are:

- [ ] https://github.com/WordPress/playground-tools/issues/316
- [ ] https://github.com/WordPress/playground-tools/issues/290 -- this one isn't 100% solvable. I've already added different descriptions to help disambiguate the buttons, but we can do a bit more.

**Comment by jonathanbossenger** [comment]
Thanks @brandonpayton 

@alexstine I can confirm that this version of the playground block is active on the Learn site, and we can test this on the [test page](https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/).

Do you have some time in the coming weeks to test the issues that @brandonpayton has linked in the comment above?

**Comment by alexstine** [comment]
@brandonpayton Two more small issues.
1. Could you please hide the arrow icon to screen readers for the Open in New Tab button? Looks like you are using the :after selector to add it so you could either add it in a span with `aria-hidden` or simply add `aria-label="Open in New Tab"` to the button.
2. For the read-only files, awesome that the button communicates that but the input field does not. Think you can open an upstream PR to get aria-readonly or HTML5 readonly support?

This has come a long way, thanks for the hard work on it.

**Comment by brandonpayton** [comment]
@alexstine, thanks for your review and continued feedback. I'm glad this is trending in the right direction!

The two new issues are logged, and I'm working on them next:
- https://github.com/WordPress/playground-tools/issues/330
- https://github.com/WordPress/playground-tools/issues/331

**Comment by jonathanbossenger** [comment]
Thanks @brandonpayton

**Comment by brandonpayton** [comment]
Hi @jonathanbossenger, a new version of the Playground block (interactive-code-block) has been released (v0.2.12) and contains updates to address the following issues:

- [ ] https://github.com/WordPress/playground-tools/issues/293
- [ ] https://github.com/WordPress/playground-tools/issues/330
- [ ] https://github.com/WordPress/playground-tools/issues/331

These issues are left open until we can confirm they are indeed fixed.

Today, with the exception of the styling issues reported [here](https://github.com/WordPress/Learn/issues/2664#issuecomment-2243041224), the remaining issues are:

- [ ] https://github.com/WordPress/playground-tools/issues/316
- [ ] https://github.com/WordPress/playground-tools/issues/290 -- we are still discussing this one.
- [ ] https://github.com/WordPress/playground-tools/issues/291 -- I am setting up a Windows VM to reproduce the issue with NVDA and hopefully confirm a fix after that.

**Comment by jonathanbossenger** [comment]
Thanks @brandonpayton 

@alexstine I can confirm that this new version has been deployed to learn.wordpress.org, which you can test on the test page.

**Comment by brandonpayton** [comment]
Hi @jonathanbossenger, a new version of the Playground block (interactive-code-block) has been released (v0.2.13), and it (along with v0.2.12) contains updates to address the following issues:

- [ ] https://github.com/WordPress/playground-tools/issues/293
- [ ] https://github.com/WordPress/playground-tools/issues/330
- [ ] https://github.com/WordPress/playground-tools/issues/331
- [ ] https://github.com/WordPress/playground-tools/issues/290
- [ ] https://github.com/WordPress/playground-tools/issues/291
- [ ] https://github.com/WordPress/playground-tools/issues/316

These issues are left open until we can confirm they are indeed fixed.

Today, the remaining a11y issue is:
- [ ] https://github.com/WordPress/playground-tools/issues/343

I'm not sure if it is a blocker, but I haven't been able to figure out a good fix for it yet.

**Comment by jonathanbossenger** [comment]
Thanks @brandonpayton 

@alexstine I can confirm that the new version of the playground block has been deployed to learn.wordpress.org. It would be greatly appreciated if you have time to test it. 

The test page is still at the following URL: https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/

**Comment by brandonpayton** [comment]
Hi @jonathanbossenger, version v0.2.14 is now released which additionally contains a fix for

- [x] https://github.com/WordPress/playground-tools/issues/344

**Comment by jonathanbossenger** [comment]
Thank you @brandonpayton.

I'm going to raise this to the training team in our weekly meeting this week, to see if we can get some more help with testing, so we can confirm that everything works as expected.

**Comment by jonathanbossenger** [comment]
@brandonpayton I've created a consolidated list of open issues related to the playground block in the main description of this issue. Could you verify that a) I've gathered all the relevant issues into that list and b) only the open issues need testing?

I am reaching out to folks to help with testing, so I want to make it easier for them to see what needs testing.

**Comment by joedolson** [comment]
I'll go through this next week.

**Comment by jonathanbossenger** [comment]
Thanks @joedolson

**Comment by brandonpayton** [comment]
> @brandonpayton I've created a consolidated list of open issues related to the playground block in the main description of this issue. Could you verify that a) I've gathered all the relevant issues into that list and b) only the open issues need testing?
> 
> I am reaching out to folks to help with testing, so I want to make it easier for them to see what needs testing.

@jonathanbossenger 

That list looks good, except that we could add:
https://github.com/WordPress/playground-tools/issues/343

I'm not sure if it is a blocker.

**Comment by brandonpayton** [comment]
@jonathanbossenger We have released v0.2.15 of the Playground block (interactive-code-block) that contains a fix for https://github.com/WordPress/playground-tools/issues/343. That issue can be added to the list above.

Thank you!

**Comment by jonathanbossenger** [comment]
Done, thanks @brandonpayton.

@joedolson it might take a day or so for the updated block to be deployed to Learn.WordPress.org for you to be able to test https://github.com/WordPress/playground-tools/issues/343

**Comment by joedolson** [comment]
This is still on my radar; but I had a client project abruptly transition from a Sept. 9 launch date to an Aug 23 launch date for emergent reasons, and it's pretty much trashed my week.

**Comment by brandonpayton** [comment]
Thank you, @joedolson. Good luck with everything!

**Comment by joedolson** [comment]
Adding a new comment so I can check these off as I confirm them.

- [ ] Playground block: A11Y: Difference between "Run" and "Activate Live Preview"? playground-tools#290
- [x] Playground block: A11Y: Powered by link needs spacing playground-tools#291
- [x] Playground block: A11Y: Add skip links for loaded preview/iFrame playground-tools#293
- [x] Playground Block: A11y: Add text documentation for keyboard exit of CodeMirror playground-tools#316
- [x] Playground block: Hide open-in-new-tab arrow icon from screen readers playground-tools#330
- [x] Playground block: Mark code editor input field as readonly when it is read only playground-tools#331
- [x] Playground block: Dismissing exit-editor-with-keyboard tip should trigger a spoken announcement playground-tools#343
- [x] Playground block: open-in-new-tab focus order is visually out-of-sequence playground-tools#344

**Comment by joedolson** [comment]
Almost everything is done here, except that I think there is a significant improvement that could be made on https://github.com/WordPress/playground-tools/issues/290. I'd recommend completing that recommendation, but then I think this is good.

**Comment by brandonpayton** [comment]
Thanks for your help, @joedolson!

@jonathanbossenger the remaining work is on my radar, and I plan to look at it next, in the next couple of days.

cc @adamziel

**Comment by brandonpayton** [comment]
@jonathanbossenger, we've released v0.2.16 of the interactive-code-block plugin with [some changes](https://github.com/WordPress/playground-tools/pull/355) in response to @joedolson's comments [here](https://github.com/WordPress/playground-tools/issues/290#issuecomment-2332444561).

The changes add:
- Updating the before-preview marker to say one of the following depending on state:
  - "Beginning of Playground Preview - Not activated"
  - "Beginning of Playground Preview - Loading"
  - "Beginning of Playground Preview - Loaded"
- Speaking "WordPress Playground loaded" after Playground completes loading in the preview iframe

**Comment by joedolson** [comment]
Just let me know when that's available for testing and I'll check it out!

**Comment by brandonpayton** [comment]
> Just let me know when that's available for testing and I'll check it out!

@jonathanbossenger, do you know if v0.2.16 is available for testing on the Learn site yet?

**Comment by jonathanbossenger** [comment]
Folks, I am so sorry, I missed this message, and it fell off my radar.

The plugin is indeed running the latest version of the playground block.

@joedolson, if you have some time, can you test the last items discussed here?

It'll be great to be able to close this out before the year wraps up.
