### ISSUE TITLE
Learning Pathways launch

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2692]
## Time

1 August 2024 9PM UTC

## Tasks

- [x] [Select Featured Courses for launch](https://github.com/orgs/WordPress/projects/40/views/26#)
- [x] [Remove progress bar and course actions from course content](https://github.com/orgs/WordPress/projects/40/views/26#)
- [x] Switch theme
- [x] Remove theme switcher
- [x] [Check browser titles](https://github.com/WordPress/Learn/issues/2603#issuecomment-2238080147)
- [x] [Ensure single lessons are indexed for search](https://github.com/WordPress/Learn/issues/2446)
- [x] [QA](https://make.wordpress.org/training/2024/07/09/lets-start-testing-learn-wordpress-org/)
