### ISSUE TITLE
Learn WordPress Course Cohort: Introduction to Plugin Development

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2942]
Planning issue for the next Learn WordPress course cohort:

https://make.wordpress.org/training/handbook/training-team-how-to-guides/course-cohorts/

**Comment by jonathanbossenger** [comment]
## Tasks

- [x] Decide on content
- [x] Decide on dates
- [x] Publish sign up post
- [x] Gather attendees
- [x] Facilitate cohort
- [ ] Publish wrap-up post

**Comment by jonathanbossenger** [comment]
## Suggested dates

1. Sign up post - Friday, October 11, 2024
2. Sign-ups close - Friday, October 25, 2024
3. Course cohort dates - Monday, 5 November, 2024 to Friday 13 December
4. Weekly Zoom calls every Wednesday during the 6-week period

**Comment by laxmariappan** [comment]
Sounds good @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Thanks @laxmariappan 

If we hold the weekly Zoom calls every Wednesday, that would be the following dates:

- 6 November
- 13 November 
- 20 November
- 27 November
- 4 December
- 11 December

Are you free for all those dates? And then, what time would you like to have the call?

**Comment by laxmariappan** [comment]
I am available on those days. Can we make it 12:00 UTC? Or any other time will work as well.

**Comment by jonathanbossenger** [comment]
Sure, I think 12:00 UTC is a good time, let's go with that.

**Comment by jonathanbossenger** [comment]
## Content

We've discussed this in Slack, but we're going to focus the cohort on an Introduction to developing plugins.

## Structure

I propose we follow the following structure:

### Prerequisite preparation and reading

Cohort participants will be required to sign up for the [Beginner WordPress Developer course](https://learn.wordpress.org/course/beginner-wordpress-developer/) and complete all the lessons in the first module on **A brief overview of how WordPress works**:

- https://learn.wordpress.org/lesson/wordpress-and-web-servers/
- https://learn.wordpress.org/lesson/the-wordpress-file-structure/
- https://learn.wordpress.org/lesson/the-wordpress-database/
- https://learn.wordpress.org/lesson/permalinks-rewriting-urls-on-apache-and-nginx/
- https://learn.wordpress.org/lesson/front-end-page-request/
- https://learn.wordpress.org/lesson/admin-page-request/

### Weekly course content to be covered

Each week, we can focus on specific topics related to beginner plugin development from this learning pathway. 

At the start of the week, we ask folks to work through the related content in the course, and then we discuss it during the Zoom call on Wednesday.

For some weeks, more than one lesson is listed under related content. This does not mean we have to cover all those lessons as part of the weekly call. Additionally, where there are only 1 or 2 lessons, it's also okay to share other resources around that topic (developer docs, developer blog posts, etc.).

**Week 1: Setting up a local development environment**

Primary objective: participants will set up a local development environment and choose a code editor 

Related content:
- https://learn.wordpress.org/lesson/local-development-environment/
- https://learn.wordpress.org/lesson/wordpress-installation/
- https://learn.wordpress.org/lesson/code-editor/

**Week 2: Basic plugin requirements**

Primary objective: participants will build their first plugin that can be activated on a WordPress site. It does not have to do anything.

Related content:
- https://learn.wordpress.org/lesson/what-is-a-plugin/
- https://learn.wordpress.org/lesson/plugin-requirements/

**Week 3: Hooks and Filters**

Primary objective: participants will learn how to use action hooks and filter hooks

Related content:
- https://learn.wordpress.org/lesson/wordpress-hooks/
- https://learn.wordpress.org/lesson/action-hooks/
- https://learn.wordpress.org/lesson/filter-hooks/
- https://learn.wordpress.org/lesson/working-with-hooks/

**Week 4: Custom post types and taxonomies**

Primary objective: participants will learn how to register a custom post type and a custom taxonomy.

Related content: 
- https://learn.wordpress.org/lesson/custom-post-types/
- https://learn.wordpress.org/lesson/custom-taxonomies/

Primary objective: participants will learn how to register and use post meta for custom data

**Week 5: Custom post type data**
Related content: 
- https://learn.wordpress.org/lesson/custom-post-type-data/

**Week 6: CSS and JavaScript**

Primary objective: participants will learn how to enqueue and use CSS and JavaScript in their plugins.

Related content: 
- https://learn.wordpress.org/lesson/enqueuing-css-or-javascript/

## After the cohort

Participants will be encouraged to complete all the other lessons in the Beginner developer course.

@laxmariappan let me know if you have any questions, comments or feedback about this suggestion.

**Comment by laxmariappan** [comment]
@jonathanbossenger everything looks great👏

I am sure the participants will get much value out of it 🙏

**Comment by jonathanbossenger** [comment]
Project thread: https://make.wordpress.org/training/2024/10/13/project-thread-the-third-learn-wordpress-course-cohort/

**Comment by jonathanbossenger** [comment]
Announcement post: https://make.wordpress.org/training/2024/10/13/announcing-the-next-learn-wordpress-course-cohort/

**Comment by jonathanbossenger** [comment]
Participant update:

42 participants signed up. Three did not have valid Slack accounts, so I had no way to contact them to invite them to the cohort.

This leaves us with 39 valid sign-ups. 

@laxmariappan has confirmed he's happy to proceed with that number. This will be the largest cohort we've run so far!

I will be reaching to out all 39 this week to confirm their participation, and adding them to the [#training-cohorts](https://app.slack.com/client/T024MFP4J/C05R97LPN8H) channel in Slack.

**Comment by jonathanbossenger** [comment]
## Participant Update:

I have DMd all valid Slack accounts today. There were an additional few participants that didn't have Slack accounts, so the current total number of potential participants is 34.

## Call planning

Based on the [cohort content structure and syllabus shared here](https://github.com/WordPress/Learn/issues/2942#issuecomment-2402350441), this is my proposal for the format for each weekly call.

**Week 1: Welcome (30 minutes) and local development environments (30 minutes)**
- Welcome all participants
- Introduce facilitators
- Allow each participant to introduce themselves (name, location, what they do with WordPress)
- An overview of local development environments
- Cover all the available options (see https://learn.wordpress.org/lesson/local-development-environment/) and anything else we want to add
- Allow time for questions related to local development environments

**Week 2: Basic plugin requirements**
- Short welcome
- Cover the basic plugin requirements
- Show creating a plugin with a plugin header, and activating it on the local WordPress site
- (optional) Cover the plugin header fields in more detail
- Questions

**Week 3: Hooks and Filters**
- Short welcome
- Cover any questions from last week
- Cover hooks and filters, and show some examples (either from the lesson or your own)
- (optional) Cover hook priority, hook parameters, and hook order
- Questions

**Week 4: Custom post types and taxonomies**
- Short welcome
- Cover any questions from last week
- Cover registering a basic custom post type and a custom taxonomy
- (optional) Cover some more of the possible parameters that can be used when registering a custom post type or custom taxonomy
- Questions

**Week 5: Custom post-type data**
- Short welcome
- Cover any questions from last week
- Custom fields, how to enable custom fields in the editor, how to add new custom fields from the Custom fields panel, how to add/edit custom fields via code
- (optional) Cover how to automatically pre-populate field names for the Custom Fields panel
- Questions

**Week 6: CSS and JavaScript**
- Short welcome
- Cover any questions from last week
- Show how to enqueue custom CSS or JavaScript
- (optional) Cover the use of parameters like dependencies and version number, also using timestamp for cache busting during development
- Wrap up cohort, inviting folks to continue with the rest of the learning pathway.

Any items marked as optional can be left out if we're running out of time, but it is suggested to prepare for these topics anyway.

## Plugin content

The lessons in the developer learning pathway create a bookstore plugin. We should follow that code as much as possible so that learners follow the same code examples from the lessons. However, we can add more things over and above the code form the lessons, as we see fit.

@laxmariappan, let me know if you have any comments/questions, or suggestions on the above plan.

**Comment by laxmariappan** [comment]
@laxmariappan this is a great plan.

I'm thinking of adding some examples and a simple quiz ( poll ) during the session

**Comment by jonathanbossenger** [comment]
Weekly Zoom meeting details

Topic: Introduction to Plugin Development course cohort
Time: Nov 6, 2024 12:00 Universal Time UTC
        Every week on Wed, 6 occurrence(s)
Please download and import the following iCalendar (.ics) files to your calendar system.
Weekly: https://us02web.zoom.us/meeting/tZwvf-2gqzsoHtL77ZsOd5fVeTxRlmoGNeFK/ics?icsToken=98tyKuGgrDMuEtGVsh2BRpw-AIqgLPzwmGJBgrdxy0jfEA9XNwXAM9ZaAL5yH__-&meetingMasterEventId=Acvri6kBSmypxaS8YkA_Yw

Join Zoom Meeting
https://us02web.zoom.us/j/88284850246?pwd=lPTA9Lu5YTNciBZu2trhcMl9NfUvrE.1

Meeting ID: 882 8485 0246
Passcode: 364025

**Comment by jonathanbossenger** [comment]
Attendee count on 20/11 - 13

**Comment by jonathanbossenger** [comment]
Posted the feedback survey results on the project thread here: https://make.wordpress.org/training/2024/10/13/project-thread-the-third-learn-wordpress-course-cohort/#comment-4423

This cohort is now wrapped up.
